SCHEMA = "postgres"

# status codes
STATUS_KEY = "status"
STATUS_CODE = "status_code"
STATUS_SUCCESS_VALUE = "success"
STATUS_FAILURE_VALUE = "failure"
SCHEMA_KEY = "schema"
TABLE_KEY = "table"
STATUS_KEY = "status"
STATUS_FAILURE_VALUE = "failed"
MESSAGE_KEY = "message"
STATUS_MESSAGE_KEY = "message"
STATUS_CODE_KEY = "status_code"
STATUS_SUCCESS_VALUE = "success"
DATA_KEY = "data"
