version: '3'

services:
  database:
    image: "postgres:latest"
    container_name: postgres-server
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ./database-data:/var/lib/postgresql/data
    networks:
      - default

  url_shortner:
    build:
      context: url_shortner
      dockerfile: Dockerfile
    container_name: url-shortner-server
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - POSTGRES_HOST=postgres-server
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    depends_on:
      - database
    networks:
      - default

networks:
  default:
