"""empty message

Revision ID: 686c8ff23115
Revises: 
Create Date: 2023-12-03 21:35:53.770849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686c8ff23115'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('url_mapper',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('long_url', sa.String(), nullable=True),
    sa.Column('url_key', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.Column('expiry_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_mapper')
    op.drop_table('user')
    # ### end Alembic commands ###
